name: Pull request tests

on:
  pull_request:
    types: [opened, reopened]

jobs:
  run:
    name: Build and run tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest tests/test_*.py

    - name: Lint with Pylint
      run: |
        python -m pip install pylint
        pylint wheresmycar
